### ISSUE TITLE
Recommend another webshell manage tool

### ISSUE THREAD

**Issue by WangYihang** [xiaoxiaoleo/xiao-webshell#2]
#### Webshell-Sniper
> https://github.com/WangYihang/Webshell-Sniper

#### Demo Video
> https://www.youtube.com/watch?v=iAUwb8SSS4s

![image](https://user-images.githubusercontent.com/16917636/39300883-c65deaf2-497f-11e8-88d6-3b9dfd80d5a6.png)

**Comment by xiaoxiaoleo** [comment]
已经添加到 https://github.com/xiaoxiaoleo/xiao-webshell/blob/master/README.md，Thanks!
